FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/proxy-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} proxy-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/proxy-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8091